### ISSUE TITLE
破解的密码怎么是不对的呢？

### ISSUE THREAD

**Issue by ITBBOOK** [dawn-lc/ArchivePasswordTestTool#17]
[广陵剑  3册,梁羽生著,深圳：海天出版社_12534238有密码.rar.zip](https://github.com/dawn-lc/ArchivePasswordTestTool/files/13679542/3._12534238.rar.zip)

原格式是rar的，请改回rar, 软件破解密码123456，但是无法解压此文件。是哪里的问题呢？

**Comment by dawn-lc** [comment]
压缩包不是标准的rar文件，7zip无法读取
